# This is tests workflow for GitHub Actions

name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: prepare for Docker image build
      run: |
        cp ./extras/docker/Dockerfile ./
        cp ./extras/docker/.dockerignore ./

    - name: build Docker image
      run: docker build -t andresriancho/w3af:test-action .

    - name: run w3af tests
      run: docker run -it andresriancho/w3af:test-action pytest
