# This is tests workflow for GitHub Actions

name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run w3af
      run: ./w3af_console

    - name: install deps
      run: /tmp/w3af_dependency_install.sh


  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run tests
      run: pytest
